[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_program = "9RgSJpdM33i5cYgmxrz5esVUeECaM5hRiRLEeHoiA2fM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/db/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
